const modules=[
 {title:'Fundamentos',tag:'MÓDULO 01',summary:'La auditoría de sistemas evalúa si la tecnología protege el negocio. No busca culpables: identifica causas, reduce riesgos y mejora procesos.',concepts:[['Propósito','Detectar riesgos, evaluar controles, investigar incidentes y elaborar informes ejecutivos.'],['Alcance','Servidores, usuarios, redes, bases de datos, aplicaciones, seguridad, respaldos, procesos e IA.'],['Auditoría financiera','Pregunta si el dinero está correcto; revisa estados, facturas y pagos.'],['Auditoría de sistemas','Pregunta si la tecnología protege al negocio; revisa información, infraestructura y riesgos.']],memory:'La mayoría de las pérdidas no nacen solo de un atacante: aparecen cuando fallan los controles internos.'},
 {title:'Riesgo y planificación',tag:'MÓDULO 02',summary:'Un auditor transforma una preocupación tecnológica en un riesgo evaluable, un control esperado y una prueba concreta.',concepts:[['Riesgo','Evento que puede fallar, valorado por su probabilidad e impacto.'],['Control','Política, sistema o revisión que previene, detecta o corrige el riesgo.'],['Plan en 6 decisiones','Objetivo, alcance, criterio, riesgos, pruebas y reporte.'],['Matriz mínima','Riesgo → control esperado → prueba de auditoría → severidad.']],memory:'Riesgo sin control = exposición. Control sin evidencia = promesa. Evidencia sin criterio = archivo bonito.'},
 {title:'Marcos de referencia',tag:'MÓDULO 03',summary:'COBIT aporta una lente de gobierno y gestión; NIST CSF ordena el riesgo de ciberseguridad; ambos dan criterios evaluables.',concepts:[['COBIT','Alinea TI con el negocio y organiza objetivos en EDM, APO, BAI, DSS y MEA.'],['NIST CSF 2.0','Seis funciones: Gobernar, Identificar, Proteger, Detectar, Responder y Recuperar.'],['Perfiles y Tiers','Permiten describir estado actual, estado objetivo y madurez de seguridad.'],['Criterio','Puede ser una política, estándar, ley, contrato, configuración aprobada o buena práctica.']],memory:'COBIT funciona como lente de gobierno; NIST CSF como mapa para ordenar el riesgo cibernético.'},
 {title:'ISACA e ITAF',tag:'MÓDULO 04',summary:'ISACA desarrolla estándares y marcos. ITAF es la metodología que guía los trabajos de auditoría y aseguramiento de TI.',concepts:[['Assurance','Generar confianza mediante evidencia objetiva, pruebas, hallazgos y conclusiones.'],['Estándares','Definen QUÉ debe hacer el auditor y son de cumplimiento obligatorio.'],['Guías','Explican CÓMO aplicar los estándares en la práctica.'],['Herramientas','Plantillas, listas de verificación y ejemplos que facilitan el trabajo.']],memory:'Un auditor profesional no improvisa: trabaja con una metodología y respalda cada conclusión.'},
 {title:'Evidencia y hallazgos',tag:'MÓDULO 05',summary:'Sin evidencia no existe un hallazgo. La conclusión debe conectar lo encontrado con el criterio, la causa, el efecto y una mejora verificable.',concepts:[['Evidencia','Puede ser física, documental, electrónica, observación o entrevista.'],['Calidad','Debe ser suficiente, apropiada, confiable, relevante y objetiva.'],['Hallazgo','Condición + criterio + causa + consecuencia + recomendación.'],['Seguimiento','Comprueba si se implementó el control y si el riesgo realmente disminuyó.']],memory:'Las entrevistas orientan, pero deben contrastarse con registros, documentos, configuraciones u observación.'}
];
const cycle=['Planeación','Evaluación de riesgos','Obtención de evidencia','Análisis','Hallazgos','Informe','Seguimiento'];
const deeper=[
 [['Diferencia entre amenaza, vulnerabilidad y riesgo','La amenaza es aquello que puede causar daño; la vulnerabilidad es la debilidad aprovechable; el riesgo es la posibilidad de que la amenaza explote esa debilidad y afecte un activo.'],['Tipos de controles','Preventivos evitan el evento; detectivos lo identifican; correctivos reducen sus efectos. Un mismo riesgo suele necesitar una combinación.'],['Pensamiento del auditor','Parte de una afirmación, identifica qué evidencia permitiría validarla, ejecuta una prueba reproducible y documenta tanto resultados positivos como excepciones.']],
 [['Objetivo y alcance auditables','Un objetivo usa verbos como evaluar o determinar y señala el control esperado. El alcance delimita procesos, sistemas, sedes, periodo y exclusiones justificadas.'],['Diseño frente a operación','La prueba de diseño pregunta si el control podría funcionar. La prueba de operación verifica con una población y muestra si funcionó consistentemente durante el periodo.'],['Severidad','La prioridad no depende de lo llamativo del problema: considera impacto, probabilidad, exposición, controles compensatorios y urgencia.']],
 [['COBIT en una auditoría','La cascada de metas relaciona necesidades del negocio con objetivos de TI. El auditor selecciona prácticas relevantes y evalúa su capacidad, no aplica el marco completo sin contexto.'],['Perfiles NIST','El perfil actual describe la realidad; el perfil objetivo define el estado deseado. La brecha permite priorizar una hoja de ruta proporcional al riesgo.'],['Cómo elegir el marco','COBIT es especialmente útil para gobierno, responsabilidades y gestión; NIST CSF para organizar resultados de ciberseguridad. Pueden complementarse.']],
 [['Principios profesionales','Integridad, objetividad, confidencialidad y competencia sostienen la confianza. Independencia y debido cuidado protegen la calidad del juicio.'],['Familias de ITAF','Los estándares generales regulan al profesional; los de desempeño orientan planificación y ejecución; los de reporte dirigen comunicación y conclusiones.'],['Certificaciones ISACA','CISA: auditoría; CISM: seguridad; CRISC: riesgos; CGEIT: gobierno de TI; CDPSE: privacidad de datos.']],
 [['Suficiencia y pertinencia','Suficiente habla de cantidad; apropiada, de calidad. Confiable atiende al origen; relevante conecta con el objetivo; objetiva puede ser corroborada.'],['Población y muestra','La población reúne todos los elementos del periodo. La muestra debe responder al riesgo y permitir explicar por qué esos elementos aportan evidencia razonable.'],['Papeles de trabajo','Deben permitir que otro auditor competente comprenda objetivo, procedimiento, fuente, muestra, resultado, excepciones y conclusión sin rehacer el trabajo.']]
];
const certifications=[
 {code:'CISA',name:'Certified Information Systems Auditor',focus:'Auditoría, control y aseguramiento de sistemas',profile:'Auditores de TI, consultores de assurance y profesionales de control interno.',domains:'Proceso de auditoría; gobierno y gestión; adquisición y desarrollo; operaciones y resiliencia; protección de activos.',experience:'5 años de experiencia profesional relevante. El examen puede presentarse antes de cumplirla; la experiencia se verifica al solicitar la certificación.',fit:'Elige CISA si quieres evaluar controles, obtener evidencia y emitir conclusiones independientes.'},
 {code:'CISM',name:'Certified Information Security Manager',focus:'Dirección y gestión de seguridad de la información',profile:'Responsables de seguridad, líderes de programas y aspirantes a CISO.',domains:'Gobierno de seguridad; gestión de riesgos; programa de seguridad; gestión de incidentes.',experience:'5 años de experiencia profesional en gestión de seguridad, cubriendo al menos 3 de sus 4 dominios.',fit:'Elige CISM si tu meta es dirigir la estrategia y el programa de seguridad, más que ejecutar controles técnicos.'},
 {code:'CRISC',name:'Certified in Risk and Information Systems Control',focus:'Riesgo tecnológico y controles de sistemas',profile:'Analistas de riesgo, propietarios de controles, consultores y profesionales GRC.',domains:'Gobierno; evaluación de riesgos de TI; respuesta y reporte; tecnología y seguridad.',experience:'3 años de experiencia profesional relevante en las áreas de práctica de CRISC.',fit:'Elige CRISC si deseas conectar escenarios tecnológicos con impacto empresarial, respuesta y monitoreo.'},
 {code:'CGEIT',name:'Certified in the Governance of Enterprise IT',focus:'Gobierno empresarial de información y tecnología',profile:'Directivos, asesores, líderes de gobierno y responsables de portafolios de TI.',domains:'Gobierno de TI empresarial; recursos de TI; realización de beneficios; optimización de riesgos.',experience:'5 años apoyando, asesorando o supervisando gobierno de TI; experiencia en al menos 3 dominios y 1 año en el dominio 1.',fit:'Elige CGEIT si trabajas en decisiones ejecutivas, alineación, beneficios, recursos y rendición de cuentas.'},
 {code:'CDPSE',name:'Certified Data Privacy Solutions Engineer',focus:'Privacidad incorporada al diseño y operación tecnológica',profile:'Ingenieros, arquitectos, desarrolladores y profesionales de privacidad técnica.',domains:'Gobierno de privacidad; arquitectura de privacidad; ciclo de vida de datos.',experience:'La certificación exige experiencia profesional aplicable; verifica en ISACA las condiciones y posibles excepciones vigentes antes de solicitarla.',fit:'Elige CDPSE si conviertes obligaciones de privacidad en requisitos, arquitectura y controles técnicos.'}
];
const risks=[
 ['Accesos y privilegios','Cuentas de excolaboradores activas, cuenta ADMIN_BANCO compartida y sin MFA administrativo.','Cruzar las bajas de RR. HH. con el directorio y revisar logs y privilegios.'],
 ['Parches y VPN','27 servidores pendientes, sistemas sin soporte y acceso VPN permanente del proveedor.','Validar inventario, criticidad, antigüedad de parches y registros de acceso remoto.'],
 ['Respaldos y recuperación','96% de éxito reportado, pero sin restauraciones en 14 meses ni copia fuera del sitio.','Observar una restauración controlada y verificar RTO/RPO y ubicación de copias.'],
 ['Fintech y datos','Copia de producción sin validación de anonimización y una clave API enviada por correo.','Examinar contrato, trazabilidad de datos, secretos y evidencia de eliminación.'],
 ['Fraude e incidentes','Reglas menos sensibles y un incidente de transferencias sin cierre formal.','Revisar cambios de reglas, alertas, tickets, escalamiento y análisis de causa raíz.']
];
const questions=[
 ['Concepto','¿Cuál describe mejor el propósito de una auditoría de sistemas?',['Buscar al empleado responsable','Evaluar si la tecnología protege el negocio y reducir riesgos','Reparar personalmente todos los sistemas','Revisar únicamente estados financieros'],1,'La auditoría analiza riesgos y controles para mejorar procesos; no se centra en castigar ni se limita a las finanzas.'],
 ['Concepto','¿Qué dos factores se combinan para valorar un riesgo?',['Costo y tiempo','Probabilidad e impacto','Hardware y software','Política y entrevista'],1,'La valoración parte de qué tan probable es el evento y qué impacto produciría.'],
 ['Aplicación','Un control existe, pero nadie conserva registros de su ejecución. ¿Qué conclusión inicial es correcta?',['El riesgo desapareció','El control es suficiente','El control es una promesa que aún debe probarse','La entrevista del gerente basta'],2,'Control sin evidencia es promesa: el auditor necesita corroborar diseño y operación.'],
 ['Marco','¿Qué marco separa gobierno de gestión y usa los dominios EDM, APO, BAI, DSS y MEA?',['NIST CSF','ITAF','COBIT','ISO 9001'],2,'COBIT organiza gobierno y gestión de información y tecnología mediante esos dominios.'],
 ['Marco','¿Cuál es la función añadida y destacada en NIST CSF 2.0?',['Facturar','Gobernar','Auditar','Certificar'],1,'Las seis funciones son Gobernar, Identificar, Proteger, Detectar, Responder y Recuperar.'],
 ['Planificación','¿Cuál opción contiene las seis decisiones del plan de auditoría vistas en clase?',['Objetivo, alcance, criterio, riesgos, pruebas y reporte','Compra, instalación, soporte, venta, cobro y cierre','Personas, dinero, edificio, fecha, firma y archivo','Amenaza, multa, culpa, sanción, despido y pago'],0,'El plan conecta esos seis elementos y delimita un trabajo viable.'],
 ['ITAF','En ITAF, los estándares definen…',['Cómo diseñar la portada','Qué debe hacer el auditor','Quién debe ser despedido','Qué software debe comprar la empresa'],1,'Los estándares establecen el qué; las guías explican el cómo y las herramientas apoyan la ejecución.'],
 ['Ética','Carlos desarrolló un sistema y es asignado para auditarlo. ¿Qué principio está amenazado?',['Disponibilidad','Independencia','Muestreo','Recuperación'],1,'Auditar el propio trabajo crea un conflicto de interés y afecta la objetividad.'],
 ['Ética','El escepticismo profesional exige…',['Desconfiar de todas las personas','Aceptar la palabra del gerente','Comprobar las afirmaciones con evidencia','Mantener secretos sin documentar'],2,'No significa acusar, sino evaluar críticamente y corroborar lo dicho.'],
 ['Evidencia','¿Cuál NO es una cualidad señalada para una buena evidencia?',['Suficiente','Confiable','Popular','Relevante'],2,'La evidencia debe ser suficiente, apropiada, confiable, relevante y objetiva.'],
 ['Evidencia','¿Por qué una entrevista normalmente debe contrastarse?',['Porque nunca puede usarse','Porque ayuda a comprender, pero requiere corroboración objetiva','Porque reemplaza todos los logs','Porque solo cuenta la evidencia física'],1,'La entrevista es válida, pero una conclusión sólida la cruza con registros, documentos u observación.'],
 ['Hallazgos','¿Qué elemento expresa “lo que debe ser” según una norma o política?',['Condición','Criterio','Causa','Consecuencia'],1,'El criterio es el referente contra el cual se compara la condición observada.'],
 ['Hallazgos','¿Cuál es el orden completo de un hallazgo?',['Criterio, multa, responsable y firma','Condición, criterio, causa, consecuencia y recomendación','Riesgo, entrevista y conclusión','Objetivo, alcance, presupuesto y contrato'],1,'Los cinco elementos conectan evidencia, deber ser, origen, impacto y acción correctiva.'],
 ['Caso NovaGuate','Los respaldos reportan 96% de éxito. ¿Qué prueba aporta mayor assurance?',['Preguntar si alguna vez fallaron','Observar una restauración controlada y conservar resultados','Confiar en el porcentaje','Crear otra presentación'],1,'Un respaldo exitoso no garantiza recuperabilidad; una prueba de restauración verifica su utilidad real.'],
 ['Caso NovaGuate','¿Qué debilidad agrava el riesgo de desastre?',['Tener 18 agencias','Guardar copia principal y secundaria en el mismo centro de datos','Ofrecer cuentas de ahorro','Usar infraestructura virtual'],1,'Un único evento físico podría afectar ambas copias y comprometer la recuperación.'],
 ['Caso NovaGuate','¿Qué evidencia pedirías primero para las cuentas de excolaboradores?',['Fotos del edificio','Listado de bajas y extracto actual del directorio','Estados financieros','Código fuente de la app móvil'],1,'El cruce permite comprobar oportunamente si las bajas fueron ejecutadas.'],
 ['Caso NovaGuate','¿Por qué la cuenta compartida ADMIN_BANCO es problemática?',['Consume más almacenamiento','Dificulta atribuir acciones a una persona','Obliga a usar MFA','Elimina todos los privilegios'],1,'Las credenciales compartidas rompen la responsabilidad individual y reducen la trazabilidad.'],
 ['Caso NovaGuate','Una copia productiva fue entregada a la fintech. ¿Qué falta crítica debe comprobarse?',['El color del logotipo','La anonimización validada y las condiciones de devolución o eliminación','La cantidad de agencias','El horario de caja'],1,'Los datos sensibles requieren protección verificable durante todo su ciclo, también con terceros.'],
 ['Caso NovaGuate','¿Cuál práctica es más riesgosa para una clave API?',['Custodiarla en un gestor de secretos','Rotarla periódicamente','Compartirla dentro de un archivo por correo','Limitar sus permisos'],2,'El correo y los archivos compartidos amplían la exposición; debe usarse gestión segura de secretos.'],
 ['Seguimiento','¿Cuándo termina realmente el ciclo de auditoría?',['Al detectar el primer error','Al entregar el informe','Al verificar controles implementados y reducción del riesgo','Al entrevistar a la gerencia'],2,'El seguimiento comprueba la implementación, el cierre y el riesgo residual, y realimenta el ciclo.'],
 ['Certificaciones','¿Qué certificación está orientada principalmente a la auditoría y assurance de sistemas?',['CISM','CISA','CGEIT','CDPSE'],1,'CISA valida capacidades para planificar y ejecutar auditorías, evaluar controles y comunicar resultados.'],
 ['Certificaciones','Una persona aspira a dirigir un programa empresarial de seguridad. ¿Qué credencial se alinea mejor?',['CISM','CISA','CDPSE','COBIT'],0,'CISM se orienta a gobierno, riesgo, programa de seguridad y gestión de incidentes.'],
 ['Certificaciones','¿Cuál certificación enfatiza la evaluación, respuesta y monitoreo del riesgo de TI?',['CGEIT','CISM','CRISC','CISA'],2,'CRISC conecta el riesgo de sistemas con controles, respuesta, reporte y negocio.'],
 ['Certificaciones','¿Qué opción corresponde a un directivo que alinea inversiones, beneficios y gobierno de TI?',['CGEIT','CDPSE','CRISC','CISA'],0,'CGEIT se dirige a funciones de dirección, asesoría y supervisión del gobierno de TI.'],
 ['Certificaciones','Un arquitecto incorpora privacidad desde el diseño y controla el ciclo de vida de datos. ¿Qué credencial es más afín?',['CISA','CISM','CDPSE','CGEIT'],2,'CDPSE vincula gobierno de privacidad con arquitectura técnica y ciclo de vida de datos.'],
 ['Certificaciones','¿Aprobar el examen equivale automáticamente a estar certificado?',['Sí, siempre','Solo para CISA','No; también deben cumplirse y verificarse los requisitos aplicables','Sí, con más de 80%'],2,'Aprobar es un paso; la certificación requiere solicitud, experiencia verificable, ética y demás condiciones.'],
 ['Certificaciones','¿Qué mantenimiento comparten estas certificaciones de ISACA?',['120 CPE cada año','20 CPE al año y 120 durante tres años','Un examen mensual','Ninguna educación continua'],1,'ISACA exige un mínimo de 20 CPE anuales y 120 en tres años.'],
 ['Certificaciones','¿Qué certificación exige actualmente un mínimo general de tres años de experiencia relevante?',['CRISC','CGEIT','CISM','CISA'],0,'CRISC establece tres años; CISA, CISM y CGEIT establecen cinco en sus requisitos generales.'],
 ['Planificación','¿Cuál objetivo está mejor formulado?',['Revisar todo TI','Determinar si las bajas de usuarios se ejecutaron oportunamente durante el último trimestre','Buscar culpables','Mejorar la empresa'],1,'Es específico, verificable y delimita control y periodo.'],
 ['Riesgos','¿Cuál enunciado formula correctamente un riesgo como evento?',['No existe MFA','Acceso no autorizado a consolas por autenticación insuficiente','Política de accesos','Instalar MFA'],1,'El riesgo describe el evento y efecto; no tener MFA es una debilidad o ausencia de control.'],
 ['Controles','Una alerta ante múltiples intentos fallidos es principalmente un control…',['Preventivo','Detectivo','Correctivo','Financiero'],1,'La alerta detecta un evento ocurrido o en curso.'],
 ['Pruebas','¿Qué diferencia una prueba de operación de una de diseño?',['Verifica funcionamiento consistente durante un periodo','Solo lee la política','Siempre usa mayor muestra','No hay diferencia'],0,'El diseño evalúa la concepción; la operación comprueba el funcionamiento real.'],
 ['Evidencia','¿Qué significa que la evidencia sea suficiente?',['Que venga de gerencia','Que su cantidad sustente razonablemente la conclusión','Que sea electrónica','Que confirme la hipótesis'],1,'Suficiencia se refiere a cantidad; apropiada se refiere a calidad.'],
 ['Caso Claro','¿Cuál control evitaría mejor DPI almacenados en teléfonos personales?',['Pedir borrado voluntario','Aplicación corporativa cifrada sin almacenamiento local','Enviarlos por correo','Cambiar la contraseña'],1,'El control se integra al proceso con captura segura, acceso mínimo, retención y borrado.'],
 ['Informe','¿Qué característica debe tener una recomendación útil?',['Ser genérica','Indicar acción concreta, responsable y verificable','Repetir la condición','Ignorar el costo'],1,'Debe ser viable, atacar la causa y permitir verificar su implementación.']
];

const nav=document.querySelector('#moduleNav'),lesson=document.querySelector('#lesson');let activeModule=0;let completed=JSON.parse(localStorage.getItem('audit-completed')||'[]');
function renderNav(){nav.innerHTML=modules.map((m,i)=>`<button class="module-btn ${i===activeModule?'active':''} ${completed.includes(i)?'done':''}" data-i="${i}"><span>${String(i+1).padStart(2,'0')} · ${m.title}</span></button>`).join('');nav.querySelectorAll('button').forEach(b=>b.onclick=()=>{activeModule=+b.dataset.i;renderNav();renderLesson()})}
function renderLesson(){const m=modules[activeModule],done=completed.includes(activeModule);lesson.innerHTML=`<div class="lesson-header"><div><span class="kicker">${m.tag}</span><h3>${m.title}</h3></div><button class="complete-btn" id="completeBtn">${done?'✓ Dominado':'Marcar como dominado'}</button></div><p class="lesson-summary">${m.summary}</p><div class="concept-grid">${m.concepts.map(c=>`<div class="concept"><b>${c[0]}</b><p>${c[1]}</p></div>`).join('')}</div><div class="lesson-deep"><span class="kicker">PROFUNDIZA</span>${deeper[activeModule].map((x,i)=>`<details ${i===0?'open':''}><summary>${x[0]}</summary><p>${x[1]}</p></details>`).join('')}${activeModule===3?`<div class="cert-intro"><h3>¿Qué certificación corresponde a tu ruta?</h3><p>Las cinco credenciales validan perfiles distintos. Aprobar el examen y obtener la certificación no siempre son el mismo paso: ISACA verifica experiencia y exige mantenimiento profesional.</p></div><div class="cert-explorer">${certifications.map((c,i)=>`<details ${i===0?'open':''}><summary><b>${c.code}</b><span>${c.focus}</span></summary><div class="cert-detail"><h4>${c.name}</h4><p><strong>Perfil:</strong> ${c.profile}</p><p><strong>Dominios:</strong> ${c.domains}</p><p><strong>Experiencia:</strong> ${c.experience}</p><p class="cert-fit"><strong>Orientación:</strong> ${c.fit}</p></div></details>`).join('')}</div><div class="cert-common"><b>Requisitos comunes de mantenimiento</b><span>Ética profesional</span><span>Educación continua</span><span>20 CPE por año</span><span>120 CPE en 3 años</span></div><p class="data-note">Información verificada con ISACA en agosto de 2026. Los requisitos pueden cambiar; confirma siempre la guía oficial antes de aplicar.</p>`:''}</div><div class="memory"><b>IDEA PARA RECORDAR</b><p>${m.memory}</p></div>`;document.querySelector('#completeBtn').onclick=()=>{completed=done?completed.filter(x=>x!==activeModule):[...completed,activeModule];localStorage.setItem('audit-completed',JSON.stringify(completed));renderNav();renderLesson()}}
renderNav();renderLesson();
document.querySelector('#cycle').innerHTML=cycle.map((x,i)=>`<div class="cycle-step"><b>0${i+1}</b><h3>${x}</h3><p>${['Define qué, por qué, alcance y recursos.','Prioriza activos, amenazas y vulnerabilidades.','Reúne pruebas de calidad.','Contrasta hechos y criterios.','Documenta los cinco elementos.','Comunica con claridad ejecutiva.','Verifica cierre y riesgo residual.'][i]}</p></div>`).join('');
document.querySelector('#riskCards').innerHTML=risks.map((r,i)=>`<article class="risk-card" tabindex="0"><span class="num">RIESGO 0${i+1}</span><h3>${r[0]}</h3><p>${r[1]}</p><div class="reveal"><b>PRUEBA INICIAL</b><br>${r[2]}</div></article>`).join('');document.querySelectorAll('.risk-card').forEach(c=>{const toggle=()=>c.classList.toggle('open');c.onclick=toggle;c.onkeydown=e=>{if(e.key==='Enter')toggle()}});
const activities=[
 {name:'Mapa de riesgos',source:'Clase 1',time:'25 min',mode:'Equipo',goal:'Aprender a priorizar lo que puede salir mal antes de proponer soluciones.',steps:['Selecciona un proceso tecnológico cercano.','Identifica al menos cinco activos.','Formula cada riesgo como un evento, no como ausencia de control.','Valora impacto y probabilidad en escala de 1 a 5.','Ordena los riesgos y defiende los tres primeros.'],deliver:'Tabla con activo, amenaza, vulnerabilidad, riesgo, impacto, probabilidad, nivel y justificación.',check:'El riesgo más alto debe poder explicarse por su efecto en el negocio, no solo por su complejidad técnica.'},
 {name:'Del riesgo a la prueba',source:'Semana 2',time:'35 min',mode:'Individual',goal:'Traducir un problema tecnológico en control, evidencia y procedimiento auditable.',steps:['Define un objetivo y alcance concretos.','Elige tres riesgos del flujo B2C.','Propón un control verificable por riesgo.','Diseña una prueba indicando población, muestra y periodo.','Establece el resultado esperado y la evidencia que conservarás.'],deliver:'Matriz de tres filas: riesgo, control esperado, prueba o evidencia y severidad.',check:'Revisa que el objetivo sea auditable, el riesgo sea un evento, la evidencia exista realmente y la severidad esté justificada.'},
 {name:'Caso pérdida Q2 millones',source:'Clase 1',time:'20 min',mode:'Debate',goal:'Separar culpa individual de causa sistémica y fallas de control.',steps:['Analiza antivirus vencido, ausencia de respaldos, permisos administrativos generales y falta de políticas.','Identifica responsables de proceso, control y supervisión.','Distingue causa inmediata de causa raíz.','Propón un control preventivo, uno detectivo y uno correctivo.'],deliver:'Conclusión ejecutiva de cinco líneas y mapa de responsabilidades.',check:'La respuesta esperada no es escoger un culpable: demuestra cómo varias fallas de control permitieron la pérdida.'},
 {name:'Plan de auditoría',source:'Semana 2',time:'40 min',mode:'Equipo',goal:'Convertir el análisis de riesgos en un encargo de auditoría viable.',steps:['Redacta objetivo general y objetivos específicos.','Delimita proceso, sistema, periodo, áreas y exclusiones.','Selecciona criterios aplicables.','Prioriza riesgos.','Asocia pruebas y define cómo se reportarán los resultados.'],deliver:'Plan de una página con las seis decisiones: objetivo, alcance, criterio, riesgos, pruebas y reporte.',check:'El alcance debe ser posible con el tiempo y recursos disponibles; cada prueba debe responder a un riesgo.'},
 {name:'ITAF · Trabajo en equipos',source:'Semana 4',time:'20 + 5 min',mode:'Equipo',goal:'Aplicar el método ITAF al caso de fotografías de DPI.',steps:['Identifica riesgos y activos afectados.','Solicita evidencia específica.','Define a quién entrevistar y qué confirmar.','Selecciona los principios profesionales relevantes.','Redacta al menos un hallazgo completo.','Presenta durante cinco minutos; el resto actúa como Comité de Auditoría.'],deliver:'Matriz breve y presentación técnica de cinco minutos.',check:'No aceptes afirmaciones sin prueba; protege datos reales y evita cualquier inspección sin autorización formal.'},
 {name:'NovaGuate integral',source:'Clase 5',time:'Proyecto',mode:'Equipo',goal:'Ejecutar de principio a fin una auditoría bancaria con enfoque ITAF.',steps:['Elabora plan y evalúa independencia.','Prioriza un mínimo de cinco riesgos.','Solicita doce evidencias y prepara seis entrevistas.','Diseña pruebas de diseño y operación.','Redacta hasta cinco hallazgos.','Prepara resumen ejecutivo, criticidad y plan de seguimiento.'],deliver:'Informe de 8 a 14 páginas más anexos y exposición de siete minutos.',check:'Rúbrica: planeación 15, riesgos 20, evidencia y pruebas 20, hallazgos 25, informe y seguimiento 15, presentación y ética 5.'}
];
let activeActivity=0;const activityTabs=document.querySelector('#activityTabs'),activityPanel=document.querySelector('#activityPanel');
function renderActivities(){activityTabs.innerHTML=activities.map((a,i)=>`<button class="activity-tab ${i===activeActivity?'active':''}" data-i="${i}">${i+1}. ${a.name}</button>`).join('');const a=activities[activeActivity];activityPanel.innerHTML=`<span class="kicker">${a.source.toUpperCase()}</span><h3>${a.name}</h3><p>${a.goal}</p><div class="activity-meta"><span>◷ ${a.time}</span><span>◎ ${a.mode}</span></div><div class="activity-columns"><div><h4>INSTRUCCIONES</h4><ol>${a.steps.map(s=>`<li>${s}</li>`).join('')}</ol></div><div><h4>ENTREGABLE</h4><p>${a.deliver}</p><div class="rubric"><b>CONTROL DE CALIDAD</b><br>${a.check}</div></div></div>`;activityTabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{activeActivity=+b.dataset.i;renderActivities()})}renderActivities();
let quiz=[],qIndex=0,score=0,locked=false;const $=s=>document.querySelector(s);
function startQuiz(){quiz=[...questions].sort(()=>Math.random()-.5).slice(0,$('#quizMode').value==='quick'?15:35);qIndex=0;score=0;$('#quizIntro').classList.add('hidden');$('#results').classList.add('hidden');$('#quizShell').classList.remove('hidden');renderQuestion()}
function renderQuestion(){locked=false;const q=quiz[qIndex];$('#quizCounter').textContent=`Pregunta ${qIndex+1} / ${quiz.length}`;$('#quizScore').textContent=`${score} pts`;$('#quizProgress').style.width=`${(qIndex/quiz.length)*100}%`;$('#questionType').textContent=q[0].toUpperCase();$('#questionText').textContent=q[1];$('#answers').innerHTML=q[2].map((a,i)=>`<button class="answer" data-i="${i}"><span>${String.fromCharCode(65+i)}.</span> ${a}</button>`).join('');$('#feedback').classList.add('hidden');$('#nextQuestion').classList.add('hidden');$('#answers').querySelectorAll('button').forEach(b=>b.onclick=()=>answer(+b.dataset.i))}
function answer(i){if(locked)return;locked=true;const q=quiz[qIndex],ok=i===q[3];if(ok)score++;$('#answers').querySelectorAll('button').forEach((b,n)=>{b.disabled=true;if(n===q[3])b.classList.add('correct');else if(n===i)b.classList.add('wrong')});$('#feedback').innerHTML=`<b>${ok?'✓ Correcto':'✕ Revisa este concepto'}</b><br>${q[4]}`;$('#feedback').classList.remove('hidden');$('#nextQuestion').classList.remove('hidden');$('#quizScore').textContent=`${score} pts`}
function next(){qIndex++;if(qIndex<quiz.length)renderQuestion();else showResults()}
function showResults(){$('#quizShell').classList.add('hidden');const pct=Math.round(score/quiz.length*100),msg=pct>=85?'Excelente criterio de auditoría.':pct>=65?'Buen avance; repasa tus errores.':'Conviene volver a la guía y reforzar conceptos.';$('#results').innerHTML=`<span class="kicker">RESULTADO FINAL</span><div class="result-score">${pct}%</div><h2>${score} de ${quiz.length}</h2><p>${msg}</p><button class="btn primary" id="retry">Intentar de nuevo →</button>`;$('#results').classList.remove('hidden');$('#retry').onclick=startQuiz;localStorage.setItem('audit-best',Math.max(pct,+(localStorage.getItem('audit-best')||0)))}
$('#startQuiz').onclick=startQuiz;$('#nextQuestion').onclick=next;$('#exitQuiz').onclick=()=>{$('#quizShell').classList.add('hidden');$('#quizIntro').classList.remove('hidden')};
const savedTheme=localStorage.getItem('audit-theme');if(savedTheme==='dark')document.body.classList.add('dark');$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('audit-theme',document.body.classList.contains('dark')?'dark':'light');$('#themeBtn').textContent=document.body.classList.contains('dark')?'☀':'☾'};if(document.body.classList.contains('dark'))$('#themeBtn').textContent='☀';
